# Generated by Django 5.0 on 2024-01-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BingoBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='section_num',
            field=models.IntegerField(default=0),
        ),
    ]
